name: Docker Image CI for GHCR

on:
    push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: npm install
              run: npm ci
            - name: run the unit tests
              run: npm test  
            - name: Build and push the image
              run: |
                docker login --username chanothy --password ${{secrets.ACCESS_TOKEN_ARITHMETIC}} ghcr.io
                docker build -t ghcr.io/chanothy/arithmetic-service:1 --file Dockerfile .  
                docker push ghcr.io/chanothy/arithmetic-service:1
            - name: Publish the image to the azure container registry
              run: |
                docker login --username practicum15timchan --password ${{secrets.AZURE_CONTAINER_REGISTRY}} practicum15timchan.azurecr.io
                docker tag ghcr.io/chanothy/arithmetic-service:1   practicum15timchan.azurecr.io/arithmetic-service:1
                docker push practicum15timchan.azurecr.io/arithmetic-service:1          

